source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GeoJSON_Example', :exclusive => true do
  pod "GeoJSON", :path => "../"
end

target 'GeoJSON_Tests', :exclusive => true do
  pod "GeoJSON", :path => "../"

  
end
